
CC=gcc
CFLAGS=-lglfw -lstdc++ -lvulkan


all:		numberextensions listextensions


numberextensions:		
		$(CC) $(CFLAGS) -o numberextensions numberextensions.cpp


listextensions:		
		$(CC) $(CFLAGS) -o listextensions listextensions.cpp
